workshopapps/twitterdevanswers.web

src/components/Section2/index.module.css
###PROFILE PAGE
added profile page
=> Feat (FE-12): build profile page

src/components/CookieBody/cookiebody.module.css, src/components/CookieHead/cookiehead.module.css
=> Fix (FE-34) - Cookie policy page style fix

src/pages/TermsOfUse/styles.css
css height property issue resolved
=> FE-16: Build Terms of Use Page

package-lock.json, src/pages/TermsOfUse/index.jsx, src/pages/TermsOfUse/styles.module.css
CSS module fix for terms of use page
=> FE-16: Build a Terms of Use Page

src/pages/Contact/styles.module.css
Fixed issue
My PR fixes FE-22
Https://linear.app/team-mallet/issue/FE-22/build-contact-page
What you were told to do
Fix styled error of contact page having padding
What did you do ?
I fixed the style disturbing the page from centering on desktop view
I am making a pull request against the dev branch (left side).
My commit messages styles matches our requested structure.
I am only making changes to files I was requested to
before changes 
After Changes
=>  FE-22 (fix: Update styles.module.css)

src/components/Tags/Devask.jsx, src/components/Tags/devask.module.css, src/pages/Settings/components/SettingsHeader/SettingsHeader.module.css, src/pages/Tags/tags.module.css
I cleaned up styles from Tags component
I cleaned up styles from Tags page
I cleaned up styles from SettingsHeader component
=> chore: clean up styles

src/components/History/History.module.css
Made changes to the wallet page to ensure responsiveness on mobile view by adding 
Previous view:
Updated view:
=> style: added changes to styles on mobile view of wallet page

src/pages/PostQuestion/PostQuestion.module.css, src/pages/PostQuestion/index.jsx, src/utils/testQuestions.json
My PR implements the 'Post a question feature' 
The Post a question section should contain 3 input boxes : The title of the question, the details of the question, and the description of the problem and attempted fixes already implemented.
I was told to link up the 'post a question' page with the dashboard page where the question will be displayed.
Create a review page and a response page which displays either success or failure to post a question.
I developed the 'post a question' page with its features and functionalities.
☑︎ My code follows the code style of this project.
☑︎ This PR does not contain plagiarized content.
☑︎ The title and description of the PR is clear and explains the approach.
☑︎ I am making a pull request against the dev branch (left side).
☑︎ My commit messages styles …
=> Feat (FE- 49) -implementing the 'post a question' functionality

src/App.jsx, src/ProtectedRoutes.jsx, src/components/Header/Header.jsx, src/components/Header/header.module.css, src/components/InternalFooter/InternalFooter.jsx, src/components/InternalFooter/internalFooter.module.css, src/components/InternalHeader/InternalHeader.jsx, src/components/InternalHeader/internalHeader.module.css, src/components/UserPage/UserProfileCard.jsx, src/index.jsx, src/pages/UserPage/userPage.jsx, src/pages/UserPage/userPage.module.css, src/pages/UserPage/users.jsx, src/store/AppContext.jsx, src/store/actionTypes.js, src/store/appReducer.js
FE-51 (https://linear.app/team-mallet/issue/FE-51/add-context-api-logic-side-bar-and-bottom-navigation-to-devask)
#Context Api
- i set up global state using context api and useReducer hook to manage state across the application
---
- i added unique sidebars to both the internal and external headers for navigation on mobile and tablet devices.
---
=> feat(FE-51): add context API logic,  internal and external sidebar for mobile navigation

src/App.jsx, src/components/History/TransactionHistory.jsx, src/pages/AuthPage/Login/index.jsx, src/pages/AuthPage/SignUp/index.jsx, src/pages/AuthPage/index.jsx, src/store/appReducer.js
Fixes Issue/Linear Ticket
Resolves ticket [FRO-54] (https://linear.app/team-mallet/issue/FE-54/add-function-to-login-and-signup-pages)
My PR Fixes FE-54
Changes proposed
I was assigned to work on linear ticket fe-54 which involves implementing contextApi to sign up and login page
i modified code and routes to ensure proper implentation
I tried to ensure responsiveness across multiple screens
I used reusable components to make the code less bulky
I am making a pull request against the dev branch (left side).
My commit messages styles matches …
=> fe-54 (feat: add functionality to signup and login page)

src/App.jsx, src/pages/Privacy/Privacy.jsx
FIX FE-62 - privacy policy page with react and css module respectively 
LINEAR LINK - https://linear.app/team-mallet/issue/FE-62/create-the-privacy-policy-page
=> privacypolicy page

src/ProtectedRoutes.jsx
to confirm authentication, the <ProtectedRoutes/> component checks if user exists in the local storage, this is because after a user successfully logs in, their credentials are stored in the application's global state  and the local storage as backup because the global state set up in react using context api and useReducer gets cleared out when there is a refresh. when user authentication is confirmed, they're are allowed access to the internal pages (protected routes), otherwise they're redirected to the login page
=> fix: added proper functionality to check authentication

src/App.jsx, src/pages/NotificationSettings/index.jsx, src/pages/NotificationSettings/styles.module.css
Notification Settings page 
( This could be an existing issue or a linear ticket )
Build notification settings page
i added notification settings to the settings page
🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.
-  [x] My code follows the code style of this project.
figma design
built page
=> Feat : Build Notification settings page

src/components/accordion/Accordion.css, src/components/accordion/Accordion.jsx, src/pages/FAQ/Index.jsx, src/pages/FAQ/Style.css
Fixes Issue/Linear Ticket
( This could be an existing issue or a linear ticket )
My PR Closes #issue_number_here or
***My PR Fixes FE-105**
**Changes proposed**
**What were you told to do?**
I was told to implement the new design of FAQ page from figma
**What did you do?**
I implemented the new design of the FAQ page from figma
🚨Please review the [style guide for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/STYLING.md) and [guidelines for contributing](https://github.com/zurichat/zc_main/blob/dev/docs/CONTRIBUTING.md) to this repository.
I am making a pull request …
=> feat: revamped the FAQ page

src/pages/Help/index.jsx, src/pages/Help/style.module.css
https://linear.app/team-mallet/issue/FE-101/revamp-help-center
my FE-101 revamps the help center page
Solution: Edited code to implement new help center design
added new stylings to current styling to style the page to match design
added responsiveness styling using media queries to make texts flexible at different screen styles
Issues: no issues , followed file structure for the whole app with eslint
screenshots:
=> Feat:FE-101 Revamp Help Center

src/components/Asks/index.jsx, src/pages/PostQuestion/index.jsx, src/pages/Profile/index.jsx
As a compeltion of the previously completed ticket [FE-107](https://linear.app/team-mallet/issue/FE-107/post-a-question-page-functionality) -  I updated the post a question page to carry the latest API endpoint URL shared with the team - api.devask.hng.tech.
=> feat: FE-107: Updated the api endpoint url to api.devask.hng.tech

src/pages/PostQuestion/PostQuestion.module.css, src/pages/PostQuestion/index.jsx, src/pages/SubmitBlog/index.jsx
I fixed styling issues on the Post a Question page at the tags and token section.
=> style: FE-107: Fixed the styling on the post a question page

.github/workflows/node.js.yml, src/pages/PostQuestion/index.jsx
FE-95
My PR Fixes FE-95/INPUT TEXT/CODE FORMATTING
I was told to implement rich code editor on every page requiring it on devask
I Implemented the rich code editor in Editor.jsx within the dashboard Page, PostQuestion page and SubmitBlog page. Also made minor changes to the style sheet of those pages to accomodate for the new implementation.This is a second pull request however to account for PostQuestion page not being merged in my last pull request.
https://user-images.githubusercontent.com/102606024/205576228-d6168b7f-e18d-4d75-b097-cbde38f25c20.mov
=> feat[FE-95]: INPUT TEXT/CODE FORMATTING

src/pages/UserPage/userPage.module.css
replaced fixed values for width on the profile cards and added aspect ratio to the card images
=> fix:fixed responsiveness of users page

src/App.jsx, src/pages/SubmitBlog/index.jsx
i fixed errors in submit blog page
=> fix: fixed errors in submit blog page

package-lock.json, package.json, src/components/Section1/index.jsx
i installed dependency for server monitoring and adjusted wallet endpoint conflict in users profile
=> fix: Dev codedlibra

src/components/UserPage/UserProfileCard.jsx, src/pages/UserPage/userPage.jsx, src/pages/UserPage/userPage.module.css, src/store/actionTypes.js, src/store/appReducer.js
=> feat: properly implemented the follow and unfollow endpoint

src/pages/UserPage/userPage.module.css
=> fix: change css jusfify-content from end to flex-end

src/pages/PostQuestion/PostQuestion.module.css, src/pages/PostQuestion/index.jsx
My PR implements the new design for 'Post question' page 
I was told to get the post question page up to date with the new design. 
I developed the 'post question' page with its features and functionalities. Remove a malfunctioning component 'Reactquill' and replaced with textarea that better suits the purpose of the page.
☑︎ My code follows the code style of this project.
☑︎ This PR does not contain plagiarized content.
☑︎ The title and description of the PR are clear and explain the approach.
☑︎ I am making a pull request against the dev branch (left side).
☑︎ My commit messages styles match our requested structure.
☑︎ My code additions will fail neither code linting checks nor unit tests.
☑︎ I am only making changes to the files I was …
=> Feat (FE-122) - IMPLEMENT NEW DESIGN FOR POST A QUESTION PAGE

src/pages/Privacy/Privacy.jsx, src/pages/Privacy/Privacy.module.css, src/pages/TermsOfUse/index.jsx, src/pages/TermsOfUse/styles.module.css
I followed all requirements both in CSS and JSX.
Link to my linear ticket https://linear.app/team-mallet/issue/FE-123/implement-new-design-for-privacy-policy-and-terms-of-use
**What I did** 
I updated all the previous text's on the pages to a new and improved one. 
I also implemented the new designs to be pixel perfect,
And made all pages mobile responsive
=> My PR  closes FE-123 linear ticket: Refactors the privacy Policy page and the Terms of use page

src/pages/NewDashboard/PostCard/PostCard.jsx, src/pages/NewDashboard/QuestionPage.jsx, src/pages/NewDashboard/ReplyCard/ReplyCard.jsx
fixed incorrect urls in PostCard.jsx, ReplyCard.jsx and Qestionpage.jsx
=> fixed incorrect url

src/pages/NewDashboard/AnswerInput/AnswerInput.jsx, src/pages/NewDashboard/AnswerInput/answerInput.module.css, src/pages/NewDashboard/NewDashboard.jsx, src/pages/NewDashboard/PostCard/postCard.module.css, src/pages/NewDashboard/QuestionPage.jsx, src/pages/NewDashboard/ReplyCard/ReplyCard.jsx, src/pages/NewDashboard/ReplyCard/replyCard.module.css, src/pages/NewDashboard/TopUsers/TopUsers.jsx, src/pages/NewDashboard/User/User.jsx, src/pages/NewDashboard/User/user.module.css, src/pages/NewDashboard/Yml/Yml.jsx, src/pages/NewDashboard/Yml/yml.module.css, src/pages/NewDashboard/YmlPost/YmlPost.jsx, src/pages/NewDashboard/YmlPost/ymlPost.module.css, src/pages/NewDashboard/newDashboard.module.css, src/pages/NewDashboard/questionPage.module.css
made adjustments to the styles for the dashboard and question pages and components to basically scale down the font sizes
=> style adjustments

src/components/InternalHeader/InternalHeader.jsx, src/components/InternalHeader/internalHeader.module.css
https://linear.app/team-mallet/issue/FE-126/implement-header-and-footer
#FE/126
My PR Fixes FE-126/ re-adjustment of the header and footer 
Changes proposed
Making necessary adjustments
Making necessary adjustments to the header and footer
I am making a pull request against the dev branch and sync fork.
My commit messages styles matches our requested structure.
My code additions will fail neither code linting checks nor unit test.
I am only making changes to files I was requested to.
=> header adjustments

src/pages/WalletPage/WalletPage.jsx
I was told to fix wallet id retrieval
i  fixed it
=> fix: Proper retrieval of wallet id

src/App.jsx, src/components/InternalHeader/InternalHeader.jsx, src/components/InternalHeader/internalHeader.module.css, src/pages/Settings/index.jsx, src/pages/Settings/styles.module.css
PR fixes the routing issues with the reset password link
PR also fixes the logout issues. It adds the logout icon with functionality to the navbar and sidebar of the internal header.
=> FEAT: Reset Password Routing Fixed

src/components/Tags/Pagination.jsx, src/components/Tags/Tag.jsx, src/components/Tags/Tag.module.css, src/pages/Tags/index.jsx, src/pages/Tags/index.module.css, src/pages/Tags/tags.module.css
My PR Fixes re-design of the tags page and responsiveness
Changes proposed
re-design the tags page and responsiveness
did as requested
I am making a pull request against the dev branch and sync fork.
My commit messages styles matches our requested structure.
My code additions will fail neither code linting checks nor unit test.
I am only making changes to files I was requested to.
=> fix: re-design of the tags page and responsiveness

src/components/ProfileHeader/index.jsx, src/components/UserActivities/index.jsx, src/pages/NewDashboard/QuestionPage.jsx, src/pages/NewDashboard/ReplyCard/ReplyCard.jsx
i corrected the usename to username on questions page and the reply card components
=> fix: corrected the usename to username

src/pages/Tags/index.jsx, src/pages/WalletPage/WalletPage.jsx
i fixed the error on the wallet page conflicting with the endpoint setup for user id
=> fix: fixed wallet error

src/pages/NewDashboard/ReplyCard/ReplyCard.jsx, src/pages/Notifications/index.jsx, src/pages/Settings/Accinfo.jsx
i corrected the toLowerCase function in notification
=> chore: corrected the toLowerCase function in notification

src/App.jsx, src/pages/VerifyAccount/VerifyAccount.module.css, src/pages/VerifyAccount/index.jsx
My PR Fixes implementation of the verify-account page
Changes proposed
implement the verify-account page
implemented the verify-account page
I am making a pull request against the dev branch and sync fork.
My commit messages styles matches our requested structure.
My code additions will fail neither code linting checks nor unit test.
I am only making changes to files I was requested to.
=> feat: implemented the verify-account page

src/pages/AdminDashboard/Skeleton/CardSkeleton.jsx, src/pages/AdminDashboard/Skeleton/styles.module.css, src/pages/AdminDashboard/index.jsx, src/pages/BlogPageReview/BlogPageReview.module.css, src/pages/BlogPageReview/index.jsx, src/pages/ManageUser/ManageUser.module.css, src/pages/ManageUser/Skeleton/CardSkeleton.jsx, src/pages/ManageUser/Skeleton/styles.module.css, src/pages/ManageUser/index.jsx, src/pages/UserBlogReview/UserBlogReview.module.css, src/pages/UserBlogReview/index.jsx
Mobile page fix for the following pages
1. blog page review  
2. manage user page
3. user blog review
Added skeleton to the following pages 
1. Admin Dashboard
2. Manage user
=> Mobile fix And Skeleton Addition
